name: 'Love of Film '
favicon: null
layout_spectrum: 0.4988
typography_spectrum: 0.24007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#404040'
    - '#797979'
    - '#b6b6b6'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
